name: CI/CD Automation Tests

on:
  push:
    branches:
      - cicd-automation

jobs:
  CICD_Automation_Tests:
    runs-on: macos-latest
    environment: Configuration Files
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Install Fastlane
        run: |
          gem install fastlane

      - name: Install Ruby Dependencies
        run: |
          bundle install

      - name: Create Release & Debug Configuration Files
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
        run: |
          echo "// Configuration settings file format documentation can be found at:" > Release.xcconfig
          echo "// https://help.apple.com/xcode/#/dev745c5c974" >> Release.xcconfig
          echo "// API 엔드 포인트 주소" >> Release.xcconfig
          echo "BASE_URL = $BASE_URL" >> Release.xcconfig
          echo "// 카카오 API 키" >> Release.xcconfig
          echo "KAKAO_API_KEY = $KAKAO_API_KEY" >> Release.xcconfig
          cat Release.xcconfig
          mv Release.xcconfig EATSSU_MVC/EATSSU_MVC/Resources

          echo "// Configuration settings file format documentation can be found at:" > Debug.xcconfig
          echo "// https://help.apple.com/xcode/#/dev745c5c974" >> Debug.xcconfig
          echo "// API 엔드 포인트 주소" >> Debug.xcconfig
          echo "BASE_URL = $BASE_URL" >> Debug.xcconfig
          echo "// 카카오 API 키" >> Debug.xcconfig
          echo "KAKAO_API_KEY = $KAKAO_API_KEY" >> Debug.xcconfig
          cat Debug.xcconfig
          mv Debug.xcconfig EATSSU_MVC/EATSSU_MVC/Resources

      - name: Install Dependencies
        run: |
          tuist install
      
      - name: Build Project
        run: |
          tuist build

      - name: Run Tests via Fastlane
        run: |
          fastlane tests