name: Continuous Integration

on:
  pull_request:
    branches:
      - qa 

jobs:
  Continuous_Integration:
    runs-on: macos-latest
    environment: Configuration Files
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)

      - name: Create Release & Debug Configuration Files
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
        run: |
          cd EATSSU_MVC/EATSSU_MVC/Resources
          mkdir Secrets
          cd Secrets

          echo "BASE_URL = $BASE_URL" >> Release.xcconfig
          echo "KAKAO_API_KEY = $KAKAO_API_KEY" >> Release.xcconfig
          cat Release.xcconfig

          echo "BASE_URL = $BASE_URL" >> Debug.xcconfig
          echo "KAKAO_API_KEY = $KAKAO_API_KEY" >> Debug.xcconfig
          cat Debug.xcconfig

      - name: Install Dependencies
        run: |
          tuist install
      
      - name: Build Project
        run: |
          tuist build