name: Upload Product

on:
  push:
    branches:
      - cd-automation

jobs:
  upload:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)