name: Upload Product

on:
  push:
    branches:
      - cd-automation

jobs:
  Distribute:
    runs-on: macos-latest
    environment: Configuration Files
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Directory Location
        run: |
          ls -la

      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)

      - name: Make Configuration File
        run: |
          touch Release.xcconfig
          echo ${{ secrets.RELEASE }} >> Release.xcconfig
          mv Release.xcconfig cd EATSSU_MVC/EATSSU_MVC/Resources

      