name: Upload Product

on:
  push:
    branches:
      - cd-automation

jobs:
  Distribute:
    runs-on: macos-latest
    environment: Configuration Files
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Directory Location
        run: |
          ls -la

      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)

      - name: Create Release.xcconfig
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
        run: |
          echo "// Configuration settings file format documentation can be found at:" > Release.xcconfig
          echo "// https://help.apple.com/xcode/#/dev745c5c974" >> Release.xcconfig
          echo "// API 엔드 포인트 주소" >> Release.xcconfig
          echo "BASE_URL = $BASE_URL" >> Release.xcconfig
          echo "// 카카오 API 키" >> Release.xcconfig
          echo "KAKAO_API_KEY = $KAKAO_API_KEY" >> Release.xcconfig

      